language: node_js
dist: trusty
sudo: required
node_js:
  - "8"

addons:
    chrome: stable

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start
env:
  matrix:
    - MODULE=alfresco-modeler-app

jobs:
    include:
        - stage: E2E Test
          script:
            ./scripts/test-e2e-ama.sh -host "localhost" -port 4100 -u "$E2E_USERNAME" -p "$E2E_PASSWORD" --unauthorized-user "$E2E_UNAUTHORIZED_USER" --unauthorized-user-password "$E2E_UNAUTHORIZED_USER_PASSWORD" -save -sh-url "$SCREENSHOT_URL" -sh-user "$SCREENSHOT_USERNAME" -sh-pass "$SCREENSHOT_PASSWORD" -dev

        - stage: Lint & Unit tests & Build
          script: npm run lint && npm run test:ci && npm run package:sdk && npm run build:prod

# Send coverage data to codecov
# after_success:
#   bash <(curl -s https://codecov.io/bash) -X gcov

cache:
  directories:
  - alfresco-modeler-app/node_modules
